import type { Project } from "../store/projectStore";
import type { Task } from "../store/taskStore";


export const statsData = {
    totalProjects: 12,
    activeProjects: 8,
    completedProjects: 4,
    totalTasks: 156,
    completedTasks: 98,
    pendingTasks: 58,
    completionRate: 62.8,
    upcomingDeadlines: 5,
    teamMembers: 3,
  };
  
// frontend/src/features/projects/data/projectsData.ts

export const projectsData: Project[] = [
  {
    id: 1,
    name: "E-commerce Platform Redesign",
    description: "Complete overhaul of the e-commerce platform with modern UI/UX, improved performance, and mobile responsiveness.",
    startDate: "2026-01-15",
    dueDate: "2026-04-30",
    priority: "high",
    status: "active",
    category: "development",
    progress: 75,
    estimatedHours: 320,
    budget: 75000,
    projectLead: "John Doe",
    clientName: "Fashion Retail Inc.",
    teamMembers: ["John Doe", "Jane Smith", "Mike Johnson", "Sarah Williams"],
    tags: ["ecommerce", "react", "ui/ux", "mobile-first"],
    goals: [
      "Launch new product catalog",
      "Implement shopping cart",
      "Integrate payment gateway",
      "Mobile responsive design"
    ],
    visibility: "team",
    requiresApproval: false,
    ownerId: 1,
    createdAt: "2026-01-10T08:00:00Z",
    updatedAt: "2026-03-15T10:30:00Z",
  },
  {
    id: 2,
    name: "Mobile App Redesign",
    description: "Redesign mobile app for better user experience and performance optimization.",
    startDate: "2026-02-01",
    dueDate: "2026-05-15",
    priority: "medium",
    status: "active",
    category: "design",
    progress: 45,
    estimatedHours: 240,
    budget: 50000,
    projectLead: "Jane Smith",
    clientName: "TechStart Mobile",
    teamMembers: ["Jane Smith", "Alex Chen", "Emily Brown"],
    tags: ["mobile", "react-native", "design-system"],
    goals: [
      "New UI components",
      "Improved navigation",
      "Dark mode support",
      "Performance optimization"
    ],
    visibility: "team",
    requiresApproval: false,
    ownerId: 1,
    createdAt: "2026-01-15T09:00:00Z",
    updatedAt: "2026-03-10T14:20:00Z",
  },
  {
    id: 3,
    name: "API Integration",
    description: "Integrate third-party APIs for payment processing and data synchronization.",
    startDate: "2026-01-10",
    dueDate: "2026-03-20",
    priority: "urgent",
    status: "active",
    category: "development",
    progress: 90,
    estimatedHours: 160,
    budget: 35000,
    projectLead: "Mike Johnson",
    clientName: "Payment Solutions Co.",
    teamMembers: ["Mike Johnson", "David Lee", "Anna Martinez"],
    tags: ["api", "backend", "payment", "integration"],
    goals: [
      "Stripe integration",
      "Webhook handling",
      "Error handling",
      "API documentation"
    ],
    visibility: "team",
    requiresApproval: false,
    ownerId: 1,
    createdAt: "2026-01-05T10:00:00Z",
    updatedAt: "2026-03-18T16:45:00Z",
  },
  {
    id: 4,
    name: "Documentation Portal",
    description: "Create comprehensive documentation portal for developers and users.",
    startDate: "2026-02-15",
    dueDate: "2026-06-01",
    priority: "low",
    status: "planning",
    category: "documentation",
    progress: 30,
    estimatedHours: 120,
    budget: 20000,
    projectLead: "Sarah Williams",
    clientName: "Internal",
    teamMembers: ["Sarah Williams", "Tom Wilson", "Lisa Anderson"],
    tags: ["docs", "technical-writing", "markdown"],
    goals: [
      "API documentation",
      "User guides",
      "Video tutorials",
      "Search functionality"
    ],
    visibility: "team",
    requiresApproval: false,
    ownerId: 1,
    createdAt: "2026-02-10T11:00:00Z",
    updatedAt: "2026-03-05T09:15:00Z",
  },
  {
    id: 5,
    name: "Marketing Campaign",
    description: "Launch digital marketing campaign for new product line.",
    startDate: "2026-03-01",
    dueDate: "2026-04-15",
    priority: "high",
    status: "active",
    category: "marketing",
    progress: 60,
    estimatedHours: 80,
    budget: 45000,
    projectLead: "Emily Brown",
    clientName: "Product Launch Team",
    teamMembers: ["Emily Brown", "Chris Taylor", "Jessica White"],
    tags: ["marketing", "social-media", "ads", "seo"],
    goals: [
      "Social media campaign",
      "Email newsletter",
      "Landing page",
      "Analytics tracking"
    ],
    visibility: "team",
    requiresApproval: true,
    ownerId: 1,
    createdAt: "2026-02-20T14:00:00Z",
    updatedAt: "2026-03-12T11:30:00Z",
  },
  {
    id: 6,
    name: "Security Audit",
    description: "Comprehensive security audit and penetration testing.",
    startDate: "2026-03-10",
    dueDate: "2026-04-30",
    priority: "urgent",
    status: "planning",
    category: "security",
    progress: 15,
    estimatedHours: 100,
    budget: 30000,
    projectLead: "David Lee",
    clientName: "Internal",
    teamMembers: ["David Lee", "Robert Chen", "Maria Garcia"],
    tags: ["security", "audit", "penetration-testing"],
    goals: [
      "Vulnerability assessment",
      "Penetration testing",
      "Security recommendations",
      "Compliance check"
    ],
    visibility: "private",
    requiresApproval: true,
    ownerId: 1,
    createdAt: "2026-03-01T09:30:00Z",
    updatedAt: "2026-03-14T13:20:00Z",
  },
  {
    id: 7,
    name: "Customer Support Platform",
    description: "Build customer support ticketing system with AI chatbot integration.",
    startDate: "2026-01-20",
    dueDate: "2026-05-30",
    priority: "medium",
    status: "active",
    category: "development",
    progress: 55,
    estimatedHours: 280,
    budget: 60000,
    projectLead: "Anna Martinez",
    clientName: "Support Solutions Inc.",
    teamMembers: ["Anna Martinez", "John Doe", "Mike Johnson", "Lisa Anderson"],
    tags: ["support", "ticketing", "chatbot", "ai"],
    goals: [
      "Ticket management",
      "AI chatbot",
      "Knowledge base",
      "Analytics dashboard"
    ],
    visibility: "team",
    requiresApproval: false,
    ownerId: 1,
    createdAt: "2026-01-18T08:45:00Z",
    updatedAt: "2026-03-16T15:10:00Z",
  },
  {
    id: 8,
    name: "Analytics Dashboard",
    description: "Create real-time analytics dashboard for business metrics.",
    startDate: "2026-02-10",
    dueDate: "2026-04-25",
    priority: "high",
    status: "onHold",
    category: "analytics",
    progress: 40,
    estimatedHours: 200,
    budget: 55000,
    projectLead: "Alex Chen",
    clientName: "Data Insights Corp",
    teamMembers: ["Alex Chen", "Tom Wilson", "Sarah Williams"],
    tags: ["analytics", "data-visualization", "real-time", "dashboard"],
    goals: [
      "Data visualization",
      "Real-time updates",
      "Export reports",
      "User permissions"
    ],
    visibility: "team",
    requiresApproval: false,
    ownerId: 1,
    createdAt: "2026-02-05T13:15:00Z",
    updatedAt: "2026-03-08T10:00:00Z",
  },
  {
    id: 9,
    name: "Cloud Migration",
    description: "Migrate infrastructure to cloud with minimal downtime.",
    startDate: "2026-03-15",
    dueDate: "2026-06-30",
    priority: "high",
    status: "planning",
    category: "infrastructure",
    progress: 10,
    estimatedHours: 400,
    budget: 90000,
    projectLead: "Robert Chen",
    clientName: "Internal",
    teamMembers: ["Robert Chen", "David Lee", "Mike Johnson"],
    tags: ["cloud", "aws", "migration", "devops"],
    goals: [
      "AWS setup",
      "Data migration",
      "Zero downtime",
      "Backup strategy"
    ],
    visibility: "private",
    requiresApproval: true,
    ownerId: 1,
    createdAt: "2026-03-10T10:00:00Z",
    updatedAt: "2026-03-17T09:30:00Z",
  },
  {
    id: 10,
    name: "Design System",
    description: "Create comprehensive design system for consistent UI across products.",
    startDate: "2026-01-05",
    dueDate: "2026-03-31",
    priority: "medium",
    status: "completed",
    category: "design",
    progress: 100,
    estimatedHours: 150,
    budget: 40000,
    projectLead: "Jessica White",
    clientName: "Internal",
    teamMembers: ["Jessica White", "Emily Brown", "Jane Smith"],
    tags: ["design", "ui", "components", "figma"],
    goals: [
      "Component library",
      "Design tokens",
      "Documentation",
      "Accessibility guidelines"
    ],
    visibility: "public",
    requiresApproval: false,
    ownerId: 1,
    createdAt: "2026-01-02T08:00:00Z",
    updatedAt: "2026-03-20T16:00:00Z",
  },
];

export const tasksData: Task[] = [
  {
    id: 1,
    title: "Complete API documentation",
    description: "Write comprehensive API documentation for the new REST endpoints including authentication, error handling, and rate limiting.",
    status: "inprogress",
    priority: "high",
    projectId: 3,
    projectName: "API Integration",
    assignee: {
      id: 2,
      name: "Jane Smith",
      email: "jane@example.com",
    },
    dueDate: "2026-03-18",
    tags: ["api", "documentation", "backend"],
    subtasks: [
      { id: 101, title: "Review existing API docs", completed: true },
      { id: 102, title: "Write endpoint descriptions", completed: true },
      { id: 103, title: "Add authentication examples", completed: false },
      { id: 104, title: "Create error response documentation", completed: false },
    ],
    attachments: [
      { id: 1001, name: "api-spec-openapi.json", size: "245 KB", url: "#" },
      { id: 1002, name: "api-examples.md", size: "128 KB", url: "#" },
    ],
    comments: [
      {
        id: 10001,
        taskId: 1,
        userId: 2,
        userName: "Jane Smith",
        content: "Don't forget to include the new authentication flow",
        createdAt: "2026-03-10T10:00:00Z",
      },
      {
        id: 10002,
        taskId: 1,
        userId: 1,
        userName: "John Doe",
        content: "I'll add the rate limiting section tomorrow",
        createdAt: "2026-03-11T14:30:00Z",
      },
    ],
    createdAt: "2026-03-01T08:00:00Z",
    updatedAt: "2026-03-15T09:00:00Z",
  },
  {
    id: 2,
    title: "Design system components",
    description: "Create reusable React components for buttons, modals, and forms following the new design system.",
    status: "inprogress",
    priority: "medium",
    projectId: 10,
    projectName: "Design System",
    assignee: {
      id: 3,
      name: "Mike Johnson",
      email: "mike@example.com",
    },
    dueDate: "2026-03-20",
    tags: ["design", "ui", "components", "react"],
    subtasks: [
      { id: 201, title: "Design button variants", completed: true },
      { id: 202, title: "Create modal component", completed: true },
      { id: 203, title: "Build form components", completed: false },
      { id: 204, title: "Write component documentation", completed: false },
    ],
    attachments: [
      { id: 2001, name: "design-system.fig", size: "1.2 MB", url: "#" },
      { id: 2002, name: "component-examples.zip", size: "3.4 MB", url: "#" },
    ],
    comments: [
      {
        id: 20001,
        taskId: 2,
        userId: 3,
        userName: "Mike Johnson",
        content: "The button component is ready for review",
        createdAt: "2026-03-12T11:00:00Z",
      },
    ],
    createdAt: "2026-03-01T09:00:00Z",
    updatedAt: "2026-03-14T15:00:00Z",
  },
  {
    id: 3,
    title: "User testing session",
    description: "Conduct user testing sessions for the mobile app redesign with 10 participants.",
    status: "todo",
    priority: "high",
    projectId: 2,
    projectName: "Mobile App Redesign",
    assignee: {
      id: 4,
      name: "Sarah Williams",
      email: "sarah@example.com",
    },
    dueDate: "2026-03-22",
    tags: ["testing", "ux", "mobile", "user-research"],
    subtasks: [
      { id: 301, title: "Recruit test participants", completed: true },
      { id: 302, title: "Create test scenarios", completed: true },
      { id: 303, title: "Conduct testing sessions", completed: false },
      { id: 304, title: "Analyze results", completed: false },
    ],
    attachments: [
      { id: 3001, name: "test-scenarios.pdf", size: "456 KB", url: "#" },
      { id: 3002, name: "feedback-form.pdf", size: "234 KB", url: "#" },
    ],
    comments: [
      {
        id: 30001,
        taskId: 3,
        userId: 4,
        userName: "Sarah Williams",
        content: "Need to confirm participant availability",
        createdAt: "2026-03-13T13:00:00Z",
      },
    ],
    createdAt: "2026-03-02T10:00:00Z",
    updatedAt: "2026-03-13T13:00:00Z",
  },
  {
    id: 4,
    title: "Security audit report",
    description: "Complete security audit and prepare detailed report with recommendations.",
    status: "todo",
    priority: "urgent",
    projectId: 6,
    projectName: "Security Audit",
    assignee: {
      id: 5,
      name: "David Lee",
      email: "david@example.com",
    },
    dueDate: "2026-03-15",
    tags: ["security", "audit", "compliance"],
    subtasks: [
      { id: 401, title: "Run vulnerability scans", completed: true },
      { id: 402, title: "Review access controls", completed: true },
      { id: 403, title: "Prepare findings report", completed: false },
      { id: 404, title: "Create remediation plan", completed: false },
    ],
    attachments: [
      { id: 4001, name: "vulnerability-report.pdf", size: "1.8 MB", url: "#" },
      { id: 4002, name: "compliance-checklist.xlsx", size: "567 KB", url: "#" },
    ],
    comments: [
      {
        id: 40001,
        taskId: 4,
        userId: 5,
        userName: "David Lee",
        content: "Found several critical vulnerabilities that need immediate attention",
        createdAt: "2026-03-14T09:00:00Z",
      },
    ],
    createdAt: "2026-03-01T11:00:00Z",
    updatedAt: "2026-03-14T09:00:00Z",
  },
  {
    id: 5,
    title: "Marketing assets review",
    description: "Review all marketing materials including social media graphics, email templates, and landing page designs.",
    status: "inprogress",
    priority: "medium",
    projectId: 5,
    projectName: "Marketing Campaign",
    assignee: {
      id: 6,
      name: "Emily Brown",
      email: "emily@example.com",
    },
    dueDate: "2026-03-19",
    tags: ["marketing", "design", "review"],
    subtasks: [
      { id: 501, title: "Review social media graphics", completed: true },
      { id: 502, title: "Check email templates", completed: false },
      { id: 503, title: "Review landing page", completed: false },
      { id: 504, title: "Finalize brand guidelines", completed: false },
    ],
    attachments: [
      { id: 5001, name: "social-assets.zip", size: "5.6 MB", url: "#" },
      { id: 5002, name: "email-templates.html", size: "89 KB", url: "#" },
    ],
    comments: [
      {
        id: 50001,
        taskId: 5,
        userId: 6,
        userName: "Emily Brown",
        content: "Social media graphics approved, waiting on email templates",
        createdAt: "2026-03-15T14:00:00Z",
      },
    ],
    createdAt: "2026-03-03T09:00:00Z",
    updatedAt: "2026-03-15T14:00:00Z",
  },
  {
    id: 6,
    title: "Cloud migration planning",
    description: "Plan the migration of infrastructure to AWS cloud with minimal downtime.",
    status: "todo",
    priority: "high",
    projectId: 9,
    projectName: "Cloud Migration",
    assignee: {
      id: 7,
      name: "Robert Chen",
      email: "robert@example.com",
    },
    dueDate: "2026-03-25",
    tags: ["cloud", "aws", "migration", "devops"],
    subtasks: [
      { id: 601, title: "Assess current infrastructure", completed: true },
      { id: 602, title: "Design cloud architecture", completed: false },
      { id: 603, title: "Create migration timeline", completed: false },
      { id: 604, title: "Plan rollback strategy", completed: false },
    ],
    attachments: [
      { id: 6001, name: "infrastructure-assessment.pdf", size: "2.1 MB", url: "#" },
      { id: 6002, name: "aws-architecture.png", size: "456 KB", url: "#" },
    ],
    comments: [],
    createdAt: "2026-03-04T10:00:00Z",
    updatedAt: "2026-03-10T16:00:00Z",
  },
  {
    id: 7,
    title: "Customer support training",
    description: "Train customer support team on new ticketing system and AI chatbot features.",
    status: "todo",
    priority: "low",
    projectId: 7,
    projectName: "Customer Support Platform",
    assignee: {
      id: 8,
      name: "Anna Martinez",
      email: "anna@example.com",
    },
    dueDate: "2026-03-28",
    tags: ["training", "support", "onboarding"],
    subtasks: [
      { id: 701, title: "Create training materials", completed: true },
      { id: 702, title: "Schedule training sessions", completed: false },
      { id: 703, title: "Conduct training", completed: false },
      { id: 704, title: "Collect feedback", completed: false },
    ],
    attachments: [
      { id: 7001, name: "training-manual.pdf", size: "3.2 MB", url: "#" },
      { id: 7002, name: "presentation-slides.pptx", size: "1.5 MB", url: "#" },
    ],
    comments: [
      {
        id: 70001,
        taskId: 7,
        userId: 8,
        userName: "Anna Martinez",
        content: "Training materials ready, waiting for schedule confirmation",
        createdAt: "2026-03-12T11:00:00Z",
      },
    ],
    createdAt: "2026-03-05T14:00:00Z",
    updatedAt: "2026-03-12T11:00:00Z",
  },
  {
    id: 8,
    title: "Analytics dashboard review",
    description: "Review the new analytics dashboard for business metrics and provide feedback.",
    status: "inprogress",
    priority: "medium",
    projectId: 8,
    projectName: "Analytics Dashboard",
    assignee: {
      id: 9,
      name: "Alex Chen",
      email: "alex@example.com",
    },
    dueDate: "2026-03-21",
    tags: ["analytics", "dashboard", "review"],
    subtasks: [
      { id: 801, title: "Test data accuracy", completed: true },
      { id: 802, title: "Review visualizations", completed: false },
      { id: 803, title: "Check performance", completed: false },
      { id: 804, title: "Provide feedback", completed: false },
    ],
    attachments: [
      { id: 8001, name: "dashboard-screenshots.pdf", size: "1.1 MB", url: "#" },
      { id: 8002, name: "metrics-definitions.xlsx", size: "234 KB", url: "#" },
    ],
    comments: [
      {
        id: 80001,
        taskId: 8,
        userId: 9,
        userName: "Alex Chen",
        content: "Data accuracy looks good, need to improve chart performance",
        createdAt: "2026-03-16T10:00:00Z",
      },
    ],
    createdAt: "2026-03-06T09:00:00Z",
    updatedAt: "2026-03-16T10:00:00Z",
  },
];